name: Publish Release

on:
  push:
    branches:
      - master
      - release-*

jobs:
  publish:
    name: Synchronize with NPM
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Tag and Publish
      uses: thefrontside/actions/synchronize-with-npm@v1.9
      env:
        GITHUB_TOKEN: ${{ secrets.FRONTSIDEJACK_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
